services:
  webapi:
    image: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=Server=Host;Port=1433;Initial Catalog=Hospital;User Id=sa;Password=Password1*
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    ports:
      - "8081:8080"
      
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1*"
      ACCEPT_EULA: "Y"
