global using SystemForSharingInfoInHospitals.Domain.Common;
global using SystemForSharingInfoInHospitals.Domain.Entities;
global using SystemForSharingInfoInHospitals.Domain.Events;
global using SystemForSharingInfoInHospitals.Domain.ValueObjects;
